### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by MarcoBeduschi** [MarcoBeduschi/tic-tac-toe-react#1]
**Behaviour**
- [ ] Player can click on squares and mark them with his mark
- [ ] Alternating turns between player and AI
- [ ] AI chooses an empty square at random
- [ ] AI makes a move on its turn
- [ ] Game is over ( no more empty squares || one of the players won )
- [ ] Freeze actions on game over (Players cannot play anymore)
- [ ] Game Reset (Play again)
- [ ] Game Start
- [ ] Assign random marks to each player on game start
- [ ] Add turn counter

**UX**
- [ ] Highlight empty square on mouse hover
- [ ] Do not hightlight marked square
- [ ] Display turn counter
